- import_tasks: proserver_fact.yaml
  when: system.features.proserver_fact
- import_tasks: hostname.yaml
  when: system.features.hostname
- import_tasks: timezone.yaml
  when: system.features.timezone
- import_tasks: netplan.yaml
  when: system.features.netplan
- import_tasks: ufw.yaml
  when: system.features.ufw
- import_tasks: sysctl.yaml
  when: system.features.sysctl
- import_tasks: hosts.yaml
  when: system.features.hosts
- import_tasks: environment.yaml
  when: system.features.environment
- import_tasks: apt.yaml
  when: system.features.apt
- import_tasks: proserver_user.yaml
  when: system.features.proserver_user
- import_tasks: postfix.yaml
  when: system.features.postfix
- import_tasks: sudoers.yaml
  when: system.features.sudoers
- import_tasks: authorized_keys.yaml
  when: system.features.authorized_keys
- import_tasks: motd.yaml
  when: system.features.motd
