- name: Make sure that sudo is installed
  ansible.builtin.package:
    name: sudo

- name: Create sudoers.d folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ system.prefix.sudoers }}/sudoers.d"
    owner: root
    state: directory

- name: Configure sudoers
  vars:
    dest: "{{ system.prefix.sudoers }}/sudoers.d/{{ item.key }}"
  loop: "{{ system.sudoers | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  ansible.builtin.copy:
    mode: "0644"
    owner: root
    content: "{{ item.value }}"
    dest: "{{ dest }}"
    validate: 'bash -c "cat /etc/sudoers %s | visudo -cf-"'
